POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Tesla",
    "password": "coil"
}

# {
#     "username": "Tesla",
#     "name": "Nikola",
#     "password": "coil"
# }

# {
#     "title": "React patterns",
#     "author": "Michael Chan",
#     "url": "https://reactpatterns.com/",
#     "likes": 7,
#     "userId": "61b176e6fa94d461561c6d3f"
# }