POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNydXppdG8iLCJpZCI6IjYxYjE5NDY3ZDUxNzFhOWM2ZThiOGNkOCIsImlhdCI6MTYzOTAyODMxM30.H76JePiIKGzDI9sopmhu5x1-pku8NEuOuQlZKUlTS08

# {
#     "username": "Cruzito",
#     "password": "ganjah"
# }

# {
#     "username": "Cruzito",
#     "name": "Cruz",
#     "password": "ganjah"
# }

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

    