POST http://localhost:3001/api/users
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc2xhIiwiaWQiOiI2MWI5OTQxZTc0NWZkYTFkM2QwYzE1Y2IiLCJpYXQiOjE2Mzk1OTM1ODd9.AGr_xLv2XWb72I-8kMlfWLtfPM0rW1mbMmJccTBP2hg

# {
#     "username": "Tesla",
#     "password": "coil"
# }

{
    "username": "Tesla",
    "name": "Nikola",
    "password": "coil"
}


# {
#     "title": "React patterns",
#     "author": "Michael Chan",
#     "url": "https://reactpatterns.com/",
#     "likes": 7
# }

# {
#   "title": "Go To Statement Considered Harmful",
#   "author": "Edsger W. Dijkstra",
#   "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
#   "likes": 5
# }

#   {
#     "title": "Canonical string reduction",
#     "author": "Edsger W. Dijkstra",
#     "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
#     "likes": 12,
#   }

#   {
#     "title": "First class tests",
#     "author": "Robert C. Martin",
#     "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
#     "likes": 10,
#   }

#   {
#     "title": "TDD harms architecture",
#     "author": "Robert C. Martin",
#     "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
#     "likes": 0,
#   }

#   {
#     "title": "Type wars",
#     "author": "Robert C. Martin",
#     "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
#     "likes": 2,
#   }

# blogs
 
#   React patterns
#   Michael Chan
#   https://reactpatterns.com/
#   7
# 

#   Go To Statement Considered Harmful
#   Edsger W. Dijkstra
#   http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html
#   5

#   Canonical string reduction
#   Edsger W. Dijkstra
#   http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html
#   12
#   

#   
#   First class tests
#   Robert C. Martin
#   http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll
#   10
#   

#   TDD harms architecture
#   Robert C. Martin
#   http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html
#   0

#   Type wars
#   Robert C. Martin
#   http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html
#   2
   